# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Curso de Arduino com Álvaro Justen
email: alvaro@cursodearduino.com.br
description: > # this means to ignore newlines until "baseurl:"
    Mais conceituado curso de Arduino do Brasil em diversas cidades, como Rio
    de Janeiro, Belo Horizonte, São Paulo, Porto Alegre e outras cidades!
    Arduino é uma plataforma de hardware e software livres que simplifica a
    criação e prototipagem de projetos de eletrônica. É possível controlar
    LEDs, motores, eletrodomésticos, comunicar-se com computadores,
    smartphones, carros, dentre muitas outras possibilidades!  Fazendo o Curso
    de Arduino você aprenderá na prática a criar projetos de automação
    residencial, robótica, ambientes interativos e outros!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cursodearduino.com.br" # the base hostname & protocol for your site
twitter_username: turicas
github_username:  turicas

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
